version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2022-ai
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_COLLATION=Polish_CI_AS
    ports:
      - "1433:1433"
    volumes:
      - ./backups:/var/opt/mssql/backups

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=YourStrong!Passw0rd
      - DOCKER_INFLUXDB_INIT_ORG=Demo
      - DOCKER_INFLUXDB_INIT_BUCKET=sql_telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dev-token
    volumes:
      - influx-data:/var/lib/influxdb2

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    depends_on:
      - influxdb
      - sqlserver
    volumes:
      # U CIEBIE plik jest w katalogu AI/telegraf/telegraf.conf
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  api:
    build:
      context: ./api/SqlTelemetryAssistant.Api
    container_name: sql-telemetry-api
    depends_on:
      - influxdb
      - sqlserver
      - ollama
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # klucz OpenAI podajesz z systemu jako zmiennÄ… OPENAI_API_KEY
      - OpenAi__ApiKey=${OPENAI_API_KEY}
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=SQLmaniak!2025
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  sql_data:
  influx-data:
  ollama-data:
  grafana-data:
